# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Climock < Formula
  desc "Mock server system for frontend development"
  homepage "https://github.com/swoozeki/climock"
  version "0.0.1"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/swoozeki/climock/releases/download/v0.0.1/climock_0.0.1_darwin_amd64.tar.gz"
      sha256 "b7f1487623464220de6819dd01e01ee280bb723f7348b3fdca718f0131cc47f3"

      def install
        bin.install "climock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/swoozeki/climock/releases/download/v0.0.1/climock_0.0.1_darwin_arm64.tar.gz"
      sha256 "de3a3980805d3eabff954c258025e6eac1cc10db75737491352a6732298c668f"

      def install
        bin.install "climock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/swoozeki/climock/releases/download/v0.0.1/climock_0.0.1_linux_amd64.tar.gz"
      sha256 "402cef5ab7d4c7e20b8c92beb277c11934b01c20f51879d31db6d1db925e67fd"
      def install
        bin.install "climock"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/swoozeki/climock/releases/download/v0.0.1/climock_0.0.1_linux_arm64.tar.gz"
      sha256 "db1c176583f9695fe0a4eb86a4ff35d6aa9179b247135a184fff669c8e7bb5df"
      def install
        bin.install "climock"
      end
    end
  end

  test do
    system "#{bin}/climock --version"
  end
end
